requires 'Mojolicious', '6.32',
requires 'DBI', '1.624',
requires 'DBD::SQLite', '0.31',
requires 'File::Pairtree', '1.02',
requires 'Mojolicious::Plugin::AssetPack', '0.68',
requires 'IO::Socket::SSL', '2.020',
